sudo: false
language: go
os:
  - linux
  - osx

# Make sure we bats
before_script:
  - git clone https://github.com/sstephenson/bats.git
  - export PATH=$PATH:bats/bin

script:
  - go get -u github.com/gosimple/slug
  - make test
